# Generated by Django 3.1.2 on 2020-10-28 09:30

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Categories', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('profilepic', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('bio', models.TextField(max_length=255)),
                ('contact', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('Image', cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image')),
                ('Description', models.TextField(max_length=255)),
                ('live_link', models.CharField(max_length=255)),
                ('design', models.IntegerField(blank=True, default='')),
                ('usability', models.IntegerField(blank=True, default='')),
                ('creativity', models.IntegerField(blank=True, default='')),
                ('content', models.IntegerField(blank=True, default='')),
                ('overall', models.IntegerField(blank=True, default='')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('categories', models.ManyToManyField(to='awards.Categories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.IntegerField(default='')),
                ('usability', models.IntegerField(default='')),
                ('content', models.IntegerField(default='')),
                ('creativity', models.IntegerField(default='')),
                ('score', models.IntegerField(default='')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.project')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.project'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
