# Generated by Django 3.1.2 on 2020-10-30 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0002_auto_20201030_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='Categories',
            new_name='title',
        ),
    ]
