# Generated by Django 3.1.2 on 2020-11-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_auto_20201101_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
