# Generated by Django 3.1.2 on 2020-11-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0006_auto_20201102_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
    ]
